string(REPEAT - 80 SPLTLINE)
# set()
function(report)
    message(${SPLTLINE})
    message("${ARGN}")
    message(${SPLTLINE})
endfunction()
# 在字符串列表中检查某一字符串是否存在(不区分大小写)
function(isInList List valueName RESULT)
    foreach(ITEM IN LISTS ${List})
        string(TOLOWER ${ITEM} CUR)
        list(APPEND LIST ${CUR})
    endforeach()

    string(TOLOWER ${valueName} newValue)

    if(${newValue} IN_LIST LIST)
        set(${RESULT} TRUE PARENT_SCOPE)
        return()
    else()
        set(${RESULT} FALSE PARENT_SCOPE)
        return()
    endif()
endfunction()